### ISSUE TITLE
Simply Booking iFrame Bug

### ISSUE THREAD

**Issue by hleise** [jose31canizar/Neno#4]
After going to the simply-booking page, the simply-booking iframe is appended to the content at the bottom of every subsequent page you visit.

**Comment by hleise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simply Booking iFrame Bug](https://trello.com/c/cfWDPbwX/11-simply-booking-iframe-bug)

**Comment by jose31canizar** [comment]
Upon refresh it goes away, so at least it's not persistent, has to do with how this iframe loads
