### ISSUE TITLE
Mobile Menu Automatically Opens

### ISSUE THREAD

**Issue by hleise** [jose31canizar/Neno#7]
Mobile menu automatically opens when shrinking the width of the page on any page that's not on the header menu. For example, go to day tours and shrink the width of the page.

**Comment by hleise** [comment]
![screen shot 2017-07-10 at 1 49 35 pm](https://user-images.githubusercontent.com/10748415/28036811-a2a0e738-6576-11e7-8ca2-9df41a047a4e.png)

**Comment by hleise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile Menu Automatically Opens](https://trello.com/c/hf7M7LT1/16-mobile-menu-automatically-opens)

**Comment by jose31canizar** [comment]
That probably is the initial state of the navbar

**Comment by hleise** [comment]
Yeah, it's odd that it's only for pages not in the navbar though. So any page that isn't booking, transportation, about, gallery, or contact.

**Comment by jose31canizar** [comment]
so this strictly only happens when the browser is originally desktop width and then shrunk to mobile?
